manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: philipjellison
      url-base: https://github.com/philipjellison
    # - name: cyboard
    #   url-base: https://github.com/Cyboard-DigitalTailor
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: philipjellison
      revision: bf4097e4c7d55242c515b882d5b75c58fb1cf590 # own fork: clear motion regs on wake
    # - name: zmk-pmw3610-driver
    #   remote: cyboard
    #   revision: startup_optimization
  self:
    path: config
